services:
    tsn.tsn.controller:
        class: tsn\tsn\controller\main
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@template'
            - '@user'
    tsn.tsn.listener:
        class: tsn\tsn\event\main_listener
        arguments:
            - '@controller.helper'
            - '@template'
        tags:
            - { name: event.listener }
